name: Deploy Source DEV

on:
  push:
    branches: ['dev']

env:
  DOMAIN_LIVE: beta.hannahsweetcakes.com
  PATH_LIVE: /home/beta-hannah/public_html

jobs:
  lintTest:
    name: Test Source
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repostitory
        uses: actions/checkout@v3
      - name: Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependecies
        run: |
          yarn install
      - name: Run Test Structure
        run: |
          yarn lint
      - name: Run Build
        run: |
          sed -i 's/next start/next start -p 9005/g' package.json
          sed -i 's/http:\/\/localhost:3000/https:\/\/beta.hannahsweetcakes.com/g' .env
          sed -i 's/api.dktech.info/apihanna.dktech.info/g' .env
          yarn build
      - name: Zip and upload to server
        run: |
          zip -qr .next.zip .next/*
          zip -qr node_modules.zip node_modules/*          
          printf "%s" "put .next.zip /home/beta-hannah/public_html" >"sftp.txt"
          sudo sshpass -p "${{ secrets.SSH_PASSWORD }}" sftp -oBatchMode=no -b sftp.txt -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          printf "%s" "put node_modules.zip /home/beta-hannah/public_html" >"sftp.txt"
          sudo sshpass -p "${{ secrets.SSH_PASSWORD }}" sftp -oBatchMode=no -b sftp.txt -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
        env:
          CI: true
  deploy:
    name: Deploy Source To Server
    runs-on: ubuntu-latest
    needs: [lintTest]
    steps:
      - name: executing remote ssh commands using password
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          command: |
            echo "Pull Source"
            cd /home/beta-hannah/public_html && git reset --hard
            cd /home/beta-hannah/public_html && git pull origin dev
            cd /home/beta-hannah/public_html && sed -i 's/next start/next start -p 9005/g' package.json
            cd /home/beta-hannah/public_html && sed -i 's/http:\/\/localhost:3000/https:\/\/beta.hannahsweetcakes.com/g' .env
            cd /home/beta-hannah/public_html && sed -i 's/api.dktech.info/apihanna.dktech.info/g' .env
            echo "*****************************************************"
            echo "Build source"
            cd /home/beta-hannah/public_html && rm -rf .next
            cd /home/beta-hannah/public_html && unzip .next.zip
            cd /home/beta-hannah/public_html && rm -rf .next.zip
            echo "Clear cache"
            rm -rf /usr/local/share/.cache/yarn/v6/*
            echo "Install source"
            cd /home/beta-hannah/public_html && yarn            
            pm2 restart hannah-beta
            echo "*********************** DONE *************************"
